### ISSUE TITLE
Installing via 3to2 produces import error

### ISSUE THREAD

**Issue by duhaime** [myint/language-check#17]
Hi, I'm on RHEL running the Anaconda distribution of Python 2.7.9. I run pip install 3to2, then copy the language_check source, cd into the source, and run `python2 setup.py install`. Everything installs correctly, but upon import I get:

<pre><code>>>> import language_check
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "language_check/__init__.py", line 238
    def check(self, text: str, srctext=None) -> [Match]:
                        ^
SyntaxError: invalid syntax</code></pre>

**Comment by duhaime** [comment]
Changing out of the source directory allowed me to import this correctly, so I'll close this issue. Whoops!
