### ISSUE TITLE
Failed import with syntax error

### ISSUE THREAD

**Issue by PhillipRatliff** [myint/language-check#24]
I've not used language-check before, so I may have missed some document explaining install, but I'm seeing this on Python 2.7, pulling from HEAD of master, when I try to run setup.py or do `import language_check{code}`

`>>> import language_check`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "language_check\__init__.py", line 241`
   ` def check(self, text: str, srctext=None) -> [Match]:`
                        ^
`SyntaxError: invalid syntax`

**Comment by PhillipRatliff** [comment]
This is what happens when you don't install 3to2lib for Python. For anyone who happens to search issues.
