### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by ramwin** [myint/language-check#26]
wangx@wangx-PC:~$ sudo pip3 install --upgrade language-check
The directory '/home/wangx/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/wangx/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting language-check
  Downloading language-check-0.8.tar.gz
Installing collected packages: language-check
  Running setup.py install for language-check ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-qkc8rg5y/language-check/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-42ihuhou-record/install-record.txt --single-version-externally-managed --compile:
    Traceback (most recent call last):
      File "/usr/lib/python3.5/urllib/request.py", line 1243, in do_open
        h.request(req.get_method(), req.selector, req.data, headers)
      File "/usr/lib/python3.5/http/client.py", line 1106, in request
        self._send_request(method, url, body, headers)
      File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
        self.endheaders(body)
      File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
        self._send_output(message_body)
      File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
        self.send(msg)
      File "/usr/lib/python3.5/http/client.py", line 877, in send
        self.connect()
      File "/usr/lib/python3.5/http/client.py", line 1252, in connect
        super().connect()
      File "/usr/lib/python3.5/http/client.py", line 849, in connect
        (self.host,self.port), self.timeout, self.source_address)
      File "/usr/lib/python3.5/socket.py", line 693, in create_connection
        for res in getaddrinfo(host, port, 0, SOCK_STREAM):
      File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
        for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    socket.gaierror: [Errno -3] Temporary failure in name resolution
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-qkc8rg5y/language-check/setup.py", line 597, in <module>
        sys.exit(main())
      File "/tmp/pip-build-qkc8rg5y/language-check/setup.py", line 592, in main
        run_setup_hooks(config)
      File "/tmp/pip-build-qkc8rg5y/language-check/setup.py", line 561, in run_setup_hooks
        language_tool_hook(config)
      File "/tmp/pip-build-qkc8rg5y/language-check/setup.py", line 586, in language_tool_hook
        download_lt()
      File "/tmp/pip-build-qkc8rg5y/language-check/download_lt.py", line 128, in download_lt
        with closing(urlopen(url)) as u:
      File "/usr/lib/python3.5/urllib/request.py", line 162, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/lib/python3.5/urllib/request.py", line 465, in open
        response = self._open(req, data)
      File "/usr/lib/python3.5/urllib/request.py", line 483, in _open
        '_open', req)
      File "/usr/lib/python3.5/urllib/request.py", line 443, in _call_chain
        result = func(*args)
      File "/usr/lib/python3.5/urllib/request.py", line 1286, in https_open
        context=self._context, check_hostname=self._check_hostname)
      File "/usr/lib/python3.5/urllib/request.py", line 1245, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-qkc8rg5y/language-check/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-42ihuhou-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-qkc8rg5y/language-check/
wangx@wangx-PC:~$

**Comment by ramwin** [comment]
Sorry, I haven't see the prerequests. Maybe I shoule install the language tool first.
