### ISSUE TITLE
Package install error in Python 3.6

### ISSUE THREAD

**Issue by userzimmermann** [myint/language-check#39]
Hi @myint :) Greetings from https://github.com/coala/coala 

Have you recently already seen something like https://travis-ci.org/coala/coala/jobs/231106820#L1027 ?

```
Collecting language-check~=1.0; extra == "alldeps" (from coala-bears[alldeps])
Exception:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/pip/download.py", line 809, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/pip/download.py", line 715, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/pip/utils/__init__.py", line 599, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/pip/utils/__init__.py", line 484, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "/opt/python/3.6.1/lib/python3.6/zipfile.py", line 1100, in __init__
    self._RealGetContents()
  File "/opt/python/3.6.1/lib/python3.6/zipfile.py", line 1168, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

We get in all of our latest PRs :/

cc @sils @jayvdb

**Comment by userzimmermann** [comment]
@myint Sorry ;) Was a travis issue: https://github.com/coala/coala/issues/4218#issuecomment-300890491
