### ISSUE TITLE
Not work in vim with the suggested settings

### ISSUE THREAD

**Issue by vanabel** [myint/language-check#47]
I use `vim-syntastic/syntastic` plugin in vim with python3 installed and install langugage_check by pip. As [syntastic](https://github.com/vim-syntastic/syntastic#faqforeign) suggest the following setting for `TeX` file, such that it view the file as `text` and use `language_check` as a checker.
```
let g:syntastic_tex_checkers = ['chktex', 'text/language_check']
```
It turns out, such setting not work on a `tex` file, the error message says:
>syntastic: error: checker output:
Traceback (most recent call last):
  File "/usr/bin/language-check", line 6, in <module>
    sys.exit(main.main())
  File "/usr/lib/python3.6/site-packages/language_check/main.py", line 113, in main
    remote_server=remote_server,
  File "/usr/lib/python3.6/site-packages/language_check/__init__.py", line 196, in __init__
    self._start_server_on_free_port()
  File "/usr/lib/python3.6/site-packages/language_check/__init__.py", line 333, in _start_server_on_
free_port
    cls._start_local_server()
  File "/usr/lib/python3.6/site-packages/language_check/__init__.py", line 377, in _start_local_serv
er
    raise Error(err_msg)
language_check.Error
syntastic: error: checker text/language_check returned abnormal status 1

Can't figure out what's wrong?

**Comment by vanabel** [comment]
I finally find the error are caused by the line:
https://github.com/myint/language-check/blob/d0b845ce97e32665bde39b8717c9c293ef372383/language_check/__init__.py#L598

Since clearly the `org.languagetool.server.HTTPServer` class does not exists in any version of  languagetool( I checked version 2.2/3.2/3.9). But I don't know how to fix it.

**Comment by myint** [comment]
Does `language-check` work on the command line for you?

**Comment by jxmorris12** [comment]
Hi! Since this project has been abandoned, I started a new fork over at https://github.com/jxmorris12/language_tool_python. 

My version supports new versions of Java and LanguageTool. `language-check` is stuck on Java 8 and LanguageTool 3.2; latest versions are Java 14 and LanguageTool 4.9!

I'm happy to help you with your issue if you raise it over at my repository! Thanks!
