### ISSUE TITLE
Overload of language_tool server

### ISSUE THREAD

**Issue by MathiasDesch** [myint/language-check#5]
Hello. I am using language-check. I have huge amount of documents to pass through language-tool in order to get their mistakes back.
It's basically a simple loop over all docs, calling your librairy.
  
    for doc in docs:
          LanguageTool.check(doc)

The start is going smoothly but after a while, performances are dropping.
Here are the symptoms :  Checking with "top" linux command, language_tool is  taking really small amount of CPU or RAM so I am assuming he is like frozen. Monitoring with wireshark I do not receive answer from my requests. When I am stopping my programm, language-tool is sending back load of http responses with the mistakes corresponding to my docs.

I tried to debug a little and here are my thoughts : might it comes from the language-check library not waiting for the requests answers, then my loop would flood language-tool with requests, which can not process anything anymore, except incoming request.
I assume this part of code is doing the call, especially the urlopen.
  
       @classmethod
    def _get_root(cls, url, data=None, num_tries=2):
        for n in xrange(num_tries):
            try:
                with urlopen(url, data, cls._TIMEOUT) as f:
                    return ElementTree.parse(f).getroot()
            except (IOError, httplib.HTTPException), e:
                if n + 1 < num_tries:
                    cls._start_server()
                else:
                    raise Error(u'{}: {}'.format(cls._url, e))

**Comment by myint** [comment]
I think I can reproduce something similar. I just simply ran `language-check` with hundreds files as its arguments. I end up getting a timeout error:

```
Traceback (most recent call last):
  File "/Users/myint/projects/language-check/3.4/lib/python3.4/site-packages/language_check-0.7.1a0-py3.4.egg/language_check/__init__.py", line 299, in _get_root
    with urlopen(url, data, cls._TIMEOUT) as f:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 463, in open
    response = self._open(req, data)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 481, in _open
    '_open', req)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 1210, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 1185, in do_open
    r = h.getresponse()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 1171, in getresponse
    response.begin()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 313, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/socket.py", line 374, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/myint/projects/language-check/3.4/bin/language-check", line 4, in <module>
    __import__('pkg_resources').run_script('language-check==0.7.1a0', 'language-check')
  File "/Users/myint/projects/language-check/3.4/lib/python3.4/site-packages/pkg_resources/__init__.py", line 696, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/myint/projects/language-check/3.4/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1614, in run_script
    exec(code, namespace, namespace)
  File "/Users/myint/projects/language-check/3.4/lib/python3.4/site-packages/language_check-0.7.1a0-py3.4.egg/EGG-INFO/scripts/language-check", line 6, in <module>
    sys.exit(main.main())
  File "/Users/myint/projects/language-check/3.4/lib/python3.4/site-packages/language_check-0.7.1a0-py3.4.egg/language_check/main.py", line 120, in main
    for match in lang_tool.check(text):
  File "/Users/myint/projects/language-check/3.4/lib/python3.4/site-packages/language_check-0.7.1a0-py3.4.egg/language_check/__init__.py", line 240, in check
    root = self._get_root(self._url, self._encode(text, srctext))
  File "/Users/myint/projects/language-check/3.4/lib/python3.4/site-packages/language_check-0.7.1a0-py3.4.egg/language_check/__init__.py", line 305, in _get_root
    raise Error('{}: {}'.format(cls._url, e))
language_check.Error: http://127.0.0.1:8081: timed out
```

**Comment by myint** [comment]
Can you reproduce the problem by running the `language-check` executable with your document filenames as argument?

**Comment by myint** [comment]
Also, what version of LanguageTool are you using? I'm using 2.2 since that is the last one that works on the Java 6.

**Comment by MathiasDesch** [comment]
After debbug a litle bit. I figure out this problem is appearing only when I am launching two concurrent python process in parrallel. I will investigate more but I am not sure anymore the problem is coming from languagecheck. It seems that my processes have higher priority than languagetool which is leading one of the process to take all the CPU time. The strange things is that one CPU is 100% used but the others are not at all.

ps :  I am currently using the languagetool version coming along with `languagecheck` which I believe is 2.7.
Thanks for you time, I am clising the issue since I do not consider it coming from languagecheck anymore..
