### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by luxe** [myint/language-check#59]
```
pip install language-check                                                                                                                                          1
Collecting language-check
  Using cached https://files.pythonhosted.org/packages/97/45/0fd1d3683d6129f30fa09143fa383cdf6dff8bc0d1648f2cf156109cb772/language-check-1.1.tar.gz
Building wheels for collected packages: language-check
  Running setup.py bdist_wheel for language-check ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_W9osa/language-check/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpYOwq7gpip-wheel- --python-tag cp27:
  Could not parse Java version from """openjdk version "10.0.1" 2018-04-17
  OpenJDK Runtime Environment (build 10.0.1+10-Ubuntu-3ubuntu1)
  OpenJDK 64-Bit Server VM (build 10.0.1+10-Ubuntu-3ubuntu1, mixed mode)
  """.
  
  ----------------------------------------
  Failed building wheel for language-check
  Running setup.py clean for language-check
Failed to build language-check
Installing collected packages: language-check
  Running setup.py install for language-check ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_W9osa/language-check/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-xKEHYl-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    Could not parse Java version from """openjdk version "10.0.1" 2018-04-17
    OpenJDK Runtime Environment (build 10.0.1+10-Ubuntu-3ubuntu1)
    OpenJDK 64-Bit Server VM (build 10.0.1+10-Ubuntu-3ubuntu1, mixed mode)
    """.
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_W9osa/language-check/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-xKEHYl-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-_W9osa/language-check/
```

**Comment by Bachstelze** [comment]
There is a wrong regex for parsing the java version. There are also already 3 pull requests to fix it, but the maintainers are too lazy to merge it.

**Comment by CapnS** [comment]
I am having this same issue, please fix it.

**Comment by rkwojdan** [comment]
We had the same problem and uninstalling java 10 and next installing java 8 solved the issue. Hope it will you, as well.

**Comment by pratik1998** [comment]
Error arises due to wrong version of openjdk. I installed oracle java 8 by following instructions from [this](http://tipsonubuntu.com/2016/07/31/install-oracle-java-8-9-ubuntu-16-04-linux-mint-18/). Now everything works fine.

**Comment by kallewesterling** [comment]
Same error happening now. I just encountered it through the `py-contractions` package that relies on `language-check`. (See issue [here](https://github.com/ian-beaver/pycontractions/issues/12).)

**Comment by nourel** [comment]
> Same error happening now. I just encountered it through the `py-contractions` package that relies on `language-check`. (See issue [here](https://github.com/ian-beaver/pycontractions/issues/12).)

same issue here. We getting this fixed soon ?

**Comment by Bachstelze** [comment]
Try to install it from this source. There isn't yet a version on pip with this bug fix.

**Comment by KorayTugberk-g** [comment]
I still can't download this package....

**Comment by SouravMalliK** [comment]
Hi,
How you use language tool in Google Cloud Function? I'm trying to deploy in GCP Cloud Function with runtime Python 3.7. I could use the library using my local virtual environment where I have java installed. But when I'm trying to deploy it in Cloud Function.. I'm getting the following error message -- 

`Function failed on loading user code. Error message: Code in file main.py can't be loaded. Did you list all required modules in requirements.txt? Detailed stack trace: Traceback (most recent call last): File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 359, in check_or_load_user_function _function_handler.load_user_function() File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 236, in load_user_function spec.loader.exec_module(main_module) File "<frozen importlib._bootstrap_external>", line 728, in exec_module File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed File "/user_code/main.py", line 10, in <module> from libraries.unknown_word import word_meaning File "/user_code/libraries/unknown_word.py", line 18, in <module> tool = language_tool_python.LanguageTool('en-IN') File "/env/local/lib/python3.7/site-packages/language_tool_python/server.py", line 46, in __init__ self._start_server_on_free_port() File "/env/local/lib/python3.7/site-packages/language_tool_python/server.py", line 183, in _start_server_on_free_port self._start_local_server() File "/env/local/lib/python3.7/site-packages/language_tool_python/server.py", line 193, in _start_local_server download_lt() File "/env/local/lib/python3.7/site-packages/language_tool_python/download_lt.py", line 144, in download_lt confirm_java_compatibility() File "/env/local/lib/python3.7/site-packages/language_tool_python/download_lt.py", line 75, in confirm_java_compatibility raise ModuleNotFoundError('No java install detected. Please install java to use language-tool-python.') ModuleNotFoundError: No java install detected. Please install java to use language-tool-python.`

Can you please provide a solution to use LanguageTool from server less functions? How can we have java environment in Cloud Function along with Python 3.7?

BR.

**Comment by MCFreddie777** [comment]
Any progress on this?

**Comment by willnaoosmith** [comment]
Same here

**Comment by katkaypettitt** [comment]
I am also having this issue, except I have java 15.0.1 installed. Would be nice to see an update.

**Comment by WarleiAlves** [comment]
Instructions for version 1.1

First, make sure you have installed Java version 6 or newest, then open a terminal and follow these steps:

1) cd /tmp 
2) wget https://files.pythonhosted.org/packages/97/45/0fd1d3683d6129f30fa09143fa383cdf6dff8bc0d1648f2cf156109cb772/language-check-1.1.tar.gz <-  pip download url 
3) tar xvfz language-check-1.1.tar.gz 
4) cd language-check-1.1 
5) nano download_lt.py <enter>

Comment out or delete everything in parse_java_version leaving only return (returning a tuple) command, as done below:

> def parse_java_version(version_text):
> 
>     """Return Java version (major1, major2).
>     >>> parse_java_version('''java version "1.6.0_65"
>     ... Java(TM) SE Runtime Environment (build 1.6.0_65-b14-462-11M4609)
>     ... Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-462, mixed mode))
>     ... ''')
>     (1, 6)
> 
>     >>> parse_java_version('''
>     ... openjdk version "1.8.0_60"
>     ... OpenJDK Runtime Environment (build 1.8.0_60-b27)
>     ... OpenJDK 64-Bit Server VM (build 25.60-b23, mixed mode))
>     ... ''')
>     (1, 8)
> 
>     """
>     # match = re.search(JAVA_VERSION_REGEX, version_text)
>     #if not match:
>     #    raise SystemExit(
>     #        'Could not parse Java version from """{}""".'.format(version_text))
> 
>     return (8, 1) # (int(match.group('major1')), int(match.group('major2')))
> 

7) save and exit nano (editor)
8) ./setup.py bdist_wheel
9) sudo ./setup.py install

**Comment by WarleiAlves** [comment]
I suggest you try to install version 6 or 8 of the JDK. I've already figured out how to install with JDK 11, but after that the package doesn't work, throwing the following exception in Java:

language_check.Error: Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException

I found that the error is caused by some changes in the java libraries after version 8.

**Comment by TejaswitaW** [comment]
I tried with 6,7,8 of the jdk, but still getting same error.

**Comment by d1sgr4c3** [comment]
still same issue in 2025
```bash
  × Running setup.py install for language-check did not run successfully.
  │ exit code: 1
  ╰─> [4 lines of output]
      Could not parse Java version from """openjdk version "21.0.6" 2025-01-21
      OpenJDK Runtime Environment (build 21.0.6+7-Ubuntu-122.04.1)
      OpenJDK 64-Bit Server VM (build 21.0.6+7-Ubuntu-122.04.1, mixed mode, sharing)
      """.
      [end of output]
```
