### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException

### ISSUE THREAD

**Issue by CyberFork** [myint/language-check#71]
In [1]: import language_check

In [2]: tool = language_check.LanguageTool('en-US')
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
<ipython-input-2-c761fa2240a1> in <module>
----> 1 tool = language_check.LanguageTool('en-US')

E:\D\Downloads\Compressed\language-check-master\language_check\__init__.py in __init__(self, language, motherTongue, remote_server)
    194             self._update_remote_server_config(self._url)
    195         elif not self._server_is_alive():
--> 196             self._start_server_on_free_port()
    197         if language is None:
    198             try:

E:\D\Downloads\Compressed\language-check-master\language_check\__init__.py in _start_server_on_free_port(cls)
    331             cls._url = 'http://{}:{}'.format(cls._HOST, cls._port)
    332             try:
--> 333                 cls._start_local_server()
    334                 break
    335             except ServerError:

E:\D\Downloads\Compressed\language-check-master\language_check\__init__.py in _start_local_server(cls)
    375                 match = cls._PORT_RE.search(err_msg)
    376                 if not match:
--> 377                     raise Error(err_msg)
    378                 port = int(match.group(1))
    379                 if port != cls._port:

Error: Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at net.loomchild.segment.srx.io.Srx2SaxParser.<init>(Srx2SaxParser.java:173)
        at org.languagetool.tokenizers.SrxTools.createSrxDocument(SrxTools.java:51)
        at org.languagetool.tokenizers.SRXSentenceTokenizer.<init>(SRXSentenceTokenizer.java:53)
        at org.languagetool.tokenizers.SimpleSentenceTokenizer.<init>(SimpleSentenceTokenizer.java:37)
        at org.languagetool.Language.<clinit>(Language.java:60)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:332)
        at org.languagetool.Languages.createLanguageObjects(Languages.java:111)
        at org.languagetool.Languages.getAllLanguages(Languages.java:97)
        at org.languagetool.Languages.<clinit>(Languages.java:39)
        at org.languagetool.language.LanguageIdentifier.getLanguageCodes(LanguageIdentifier.java:77)
        at org.languagetool.language.LanguageIdentifier.<init>(LanguageIdentifier.java:64)
        at org.languagetool.server.LanguageToolHttpHandler.<init>(LanguageToolHttpHandler.java:85)
        at org.languagetool.server.HTTPServer.<init>(HTTPServer.java:99)
        at org.languagetool.server.HTTPServer.main(HTTPServer.java:145)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 15 more

**Comment by CyberFork** [comment]
Use java version "1.8.0_202" fixed it.

**Comment by CyberFork** [comment]
Use java 12 before
