### ISSUE TITLE
Issue on Windows installation

### ISSUE THREAD

**Issue by DykVanDyke** [myint/language-check#82]
Hello, 

I could'nt install this package using the pip standard option (see bellow error), but it worked by downloading the sources and using the local install option from pip like so:

`python -m pip install -e .`

My machine settings are the following:

```
Windows 11
python 3.11.3
pip 23.1.2
```

It could be nice to newbies in Python (like myself) to correct the issue.

**The error when installing the package using standart pip options:**

```
python -m pip install language-check
Collecting language-check
  Using cached language-check-1.1.tar.gz (33 kB)
  Preparing metadata (setup.py) ... done
Installing collected packages: language-check
  DEPRECATION: language-check is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for language-check ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for language-check did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\userXYZ\AppData\Local\Temp\pip-install-8rn225jr\language-check_ba125eb5204948dda086bfec95f6c3c0\setup.py", line 595, in <module>
          sys.exit(main())
                   ^^^^^^
        File "C:\Users\userXYZ\AppData\Local\Temp\pip-install-8rn225jr\language-check_ba125eb5204948dda086bfec95f6c3c0\setup.py", line 590, in main
          run_setup_hooks(config)
        File "C:\Users\userXYZ\AppData\Local\Temp\pip-install-8rn225jr\language-check_ba125eb5204948dda086bfec95f6c3c0\setup.py", line 561, in run_setup_hooks
          language_tool_hook(config)
        File "C:\Users\userXYZ\AppData\Local\Temp\pip-install-8rn225jr\language-check_ba125eb5204948dda086bfec95f6c3c0\setup.py", line 584, in language_tool_hook
          download_lt()
        File "C:\Users\userXYZ\AppData\Local\Temp\pip-install-8rn225jr\language-check_ba125eb5204948dda086bfec95f6c3c0\download_lt.py", line 128, in download_lt
          with closing(urlopen(url)) as u:
                       ^^^^^^^^^^^^
        File "C:\Users\userXYZ\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 216, in urlopen
          return opener.open(url, data, timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\userXYZ\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 525, in open
          response = meth(req, response)
                     ^^^^^^^^^^^^^^^^^^^
        File "C:\Users\userXYZ\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 634, in http_response
          response = self.parent.error(
                     ^^^^^^^^^^^^^^^^^^
        File "C:\Users\userXYZ\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 557, in error
          result = self._call_chain(*args)
                   ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\userXYZ\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 496, in _call_chain
          result = func(*args)
                   ^^^^^^^^^^^
        File "C:\Users\userXYZ\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 749, in http_error_302
          return self.parent.open(new, timeout=req.timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\userXYZ\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 525, in open
          response = meth(req, response)
                     ^^^^^^^^^^^^^^^^^^^
        File "C:\Users\userXYZ\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 634, in http_response
          response = self.parent.error(
                     ^^^^^^^^^^^^^^^^^^
        File "C:\Users\userXYZ\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 563, in error
          return self._call_chain(*args)
                 ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\userXYZ\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 496, in _call_chain
          result = func(*args)
                   ^^^^^^^^^^^
        File "C:\Users\userXYZ\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 643, in http_error_default
          raise HTTPError(req.full_url, code, msg, hdrs, fp)
      urllib.error.HTTPError: HTTP Error 403: Forbidden
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> language-check

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

```

**Comment by jameshartzell** [comment]
same issue here

**Comment by scillidan** [comment]
I used `python39`:

```sh
python39 -m venv venv
venv\Scripts\activate.bat
pip install -e .
```

```sh
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Obtaining file:///D:/srcr/gd_language-check
  Preparing metadata (setup.py) ... done
Installing collected packages: language-check
  Running setup.py develop for language-check
Successfully installed language-check-1.1
WARNING: You are using pip version 22.0.4; however, version 23.3.2 is available.
You should consider upgrading via the 'D:\srcr\gd_language-check\venv\Scripts\python.exe -m pip install --upgrade pip' command.
```

I guess you maybe should check the network environment. It says `HTTP Error 403`. Or use an older version of python.
